name: Upload-benchmarks

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

jobs:
  # This is copied from tests.yml
  build-core:
    name: Build semgrep-core
    runs-on: ubuntu-latest
    container: returntocorp/ocaml:alpine
    steps:
      - name: Pre-checkout fixes
        run: |
          sudo chmod -R 777 /github
          github_cache_dir="/__w"
          sudo mkdir -p "$github_cache_dir"
          sudo chmod -R 777 "$github_cache_dir"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Post-checkout fixes
        run: ./.github/post-checkout
      - name: Build semgrep-core and spacegrep
        run: ./scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ocaml-build-artifacts
          path: ocaml-build-artifacts.tgz

  upload-benchmarks:
    name: upload benchmarks to dashboard
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts/ocaml-build-artifacts.tgz
          sudo cp ocaml-build-artifacts/bin/* /usr/bin
      - name: Install semgrep
        run: |
          cd semgrep
          pip3 install pipenv
          pipenv install --dev
      - name: Upload benchmark timings
        run: |
          cd semgrep
          pipenv run semgrep --version
          pipenv run python -m semgrep --version
          pipenv run semgrep-core -version
          pipenv run python3 ../perf/run-benchmarks --upload
